const words = [
  "Abstemious",
  "Bellicose",
  "Circumlocution",
  "Dichotomy",
  "Ebullient",
  "Fastidious",
  "Grandiloquent",
  "Heterogeneous",
  "Idiosyncrasy",
  "Juxtaposition",
  "Kaleidoscopic",
  "Lugubrious",
  "Mendacious",
  "Nihilistic",
  "Obsequious",
  "Parsimonious",
  "Querulous",
  "Rancorous",
  "Sagacious",
  "Temerarious",
  "Ubiquitous",
  "Vociferous",
  "Welter",
  "Xenophobia",
  "Yoke",
  "Zealotry",
];

export default words;
